export const OFFER_MAKE_REQUEST = 'OFFER_MAKE_REQUEST'
export const OFFER_MAKE_SUCCESS = 'OFFER_MAKE_SUCCESS'
export const OFFER_MAKE_FAIL = 'OFFER_MAKE_FAIL'

export const OFFER_LIST_REQUEST = 'OFFER_LIST_REQUEST'
export const OFFER_LIST_SUCCESS = 'OFFER_LIST_SUCCESS'
export const OFFER_LIST_FAIL = 'OFFER_LIST_FAIL'
